author: Kevin Moore <github@j832.com>
description: A dart wrapper around the git command line
documentation: http://kevmoo.github.io/git.dart/
homepage: https://github.com/kevmoo/git.dart
name: git
version: 0.4.1+1
dependencies: 
  bot: '>=0.26.0 <0.28.0'
  path: '>=1.0.0 <2.0.0'
dependency_overrides: 
dev_dependencies: 
  hop: '>=0.30.4+1 <0.32.0'
  hop_docgen: '>=0.1.2+5 <0.2.0'
  hop_unittest: '>=0.1.0 <0.2.0'
  scheduled_test: '>=0.10.0 <0.12.0'
environment: 
  sdk: '>=1.9.0 <2.0.0'
